export const loadLoginPage = () => import('../pages/Login');
export const loadAuthCallbackPage = () => import('../pages/AuthCallback');
export const loadDashboardPage = () => import('../pages/Dashboard');
export const loadQuotesPage = () => import('../pages/QuotesPage');
export const loadQuoteEditorPage = () => import('../pages/QuoteEditor');
export const loadQuotePresentationPage = () => import('../pages/QuotePresentationPage');
export const loadClientsPage = () => import('../pages/ClientsPage');
export const loadCrisisManagementPage = () => import('../pages/CrisisManagementPage');
export const loadInstallationPage = () => import('../pages/InstallationPage');
export const loadInventoryPage = () => import('../pages/InventoryPage');
export const loadWarehousePage = () => import('../pages/WarehousePage');
export const loadEmployeesPage = () => import('../pages/EmployeesPage');
export const loadMaterialsPage = () => import('../pages/MaterialsPage');
export const loadAdminPage = () => import('../pages/AdminPage');
export const loadProfilePage = () => import('../pages/ProfilePage');
export const loadReportsPage = () => import('../pages/ReportsPage');
export const loadProjectsPage = () => import('../pages/ProjectsPage');
export const loadCalendarPage = () => import('../pages/CalendarPage');

export const preloadRoute = (path: string) => {
  if (path === '/') return loadDashboardPage();
  if (path.startsWith('/proposta/')) return loadQuotePresentationPage();
  if (path.startsWith('/quotes/new') || path.startsWith('/quotes/edit/')) return loadQuoteEditorPage();
  if (path.startsWith('/quotes') || path.startsWith('/history')) return loadQuotesPage();
  if (path.startsWith('/projects')) return loadProjectsPage();
  if (path.startsWith('/calendar')) return loadCalendarPage();
  if (path.startsWith('/clients')) return loadClientsPage();
  if (path.startsWith('/crisis')) return loadCrisisManagementPage();
  if (path.startsWith('/installation')) return loadInstallationPage();
  if (path.startsWith('/reports')) return loadReportsPage();
  if (path.startsWith('/materials')) return loadMaterialsPage();
  if (path.startsWith('/inventory')) return loadInventoryPage();
  if (path.startsWith('/warehouse')) return loadWarehousePage();
  if (path.startsWith('/employees')) return loadEmployeesPage();
  if (path.startsWith('/admin')) return loadAdminPage();
  if (path.startsWith('/profile')) return loadProfilePage();
  if (path.startsWith('/auth/confirm')) return loadAuthCallbackPage();
  if (path.startsWith('/login')) return loadLoginPage();
  return Promise.resolve();
};
