export const loadLoginPage = () => import('../pages/Login');
export const loadDashboardPage = () => import('../pages/Dashboard');
export const loadQuotesPage = () => import('../pages/QuotesPage');
export const loadQuoteEditorPage = () => import('../pages/QuoteEditor');
export const loadClientsPage = () => import('../pages/ClientsPage');
export const loadInventoryPage = () => import('../pages/InventoryPage');
export const loadMaterialsPage = () => import('../pages/MaterialsPage');
export const loadAdminPage = () => import('../pages/AdminPage');
export const loadProfilePage = () => import('../pages/ProfilePage');
export const loadReportsPage = () => import('../pages/ReportsPage');
export const loadPremiumProposalPage = () => import('../pages/PremiumProposalPage');
export const loadProjectsPage = () => import('../pages/ProjectsPage');
export const loadCalendarPage = () => import('../pages/CalendarPage');

export const preloadRoute = (path: string) => {
  if (path === '/') return loadDashboardPage();
  if (path.startsWith('/quotes/proposal/')) return loadPremiumProposalPage();
  if (path.startsWith('/quotes/new') || path.startsWith('/quotes/edit/')) return loadQuoteEditorPage();
  if (path.startsWith('/quotes') || path.startsWith('/history')) return loadQuotesPage();
  if (path.startsWith('/projects')) return loadProjectsPage();
  if (path.startsWith('/calendar')) return loadCalendarPage();
  if (path.startsWith('/clients')) return loadClientsPage();
  if (path.startsWith('/reports')) return loadReportsPage();
  if (path.startsWith('/materials')) return loadMaterialsPage();
  if (path.startsWith('/inventory')) return loadInventoryPage();
  if (path.startsWith('/admin')) return loadAdminPage();
  if (path.startsWith('/profile')) return loadProfilePage();
  if (path.startsWith('/login')) return loadLoginPage();
  return Promise.resolve();
};
