insert into public.inventory (id, material_id, material_name, code, provider, rack_id, category, material_line, material_type, thickness_label, texture, length, width, thickness, area, cost, minimum_sale_price, status, notes, photo_url, loss_reason, loss_notes, loss_quote_id, loss_client_id, loss_client_name, loss_piece_id, loss_piece_name, lost_by_uid, lost_by_name, lost_at, created_at, updated_at)
values
  ('MrHYTpDBfOapmfjk9faZ', 'quartzito-botanic-green', 'Botanic Green', '5151', '', 'rack_2', 'Quartzito', 'Super Premium', 'Chapa', '2cm', 'Polido', 155, 551, 2, 8.5405, 5155, 9215, 'Disponível', '', null, null, null, null, null, null, null, null, null, null, null, timezone('utc', now()), timezone('utc', now())),
  ('os9mbtB8jNKo90Xi2wLD', 'alba-oro', 'Alba Oro', '23232', '', 'rack_1', 'Mármore', 'Premium', 'Chapa', '2cm', 'Polido', 322, 323, 2, 10.4006, 2333, 4444, 'Disponível', '', null, null, null, null, null, null, null, null, null, null, null, timezone('utc', now()), timezone('utc', now())),
  ('OBL37ZSIGcVp95b7kLyY', 'quartzito-botanic-green', 'Botanic Green', '5151', '', 'rack_2', 'Quartzito', 'Super Premium', 'Chapa', '2cm', 'Polido', 155, 551, 2, 8.5405, 5155, 9215, 'Disponível', '', null, null, null, null, null, null, null, null, null, null, null, timezone('utc', now()), timezone('utc', now()))
on conflict (id) do update set
  material_id = excluded.material_id,
  material_name = excluded.material_name,
  code = excluded.code,
  provider = excluded.provider,
  rack_id = excluded.rack_id,
  category = excluded.category,
  material_line = excluded.material_line,
  material_type = excluded.material_type,
  thickness_label = excluded.thickness_label,
  texture = excluded.texture,
  length = excluded.length,
  width = excluded.width,
  thickness = excluded.thickness,
  area = excluded.area,
  cost = excluded.cost,
  minimum_sale_price = excluded.minimum_sale_price,
  status = excluded.status,
  notes = excluded.notes,
  photo_url = excluded.photo_url,
  loss_reason = excluded.loss_reason,
  loss_notes = excluded.loss_notes,
  loss_quote_id = excluded.loss_quote_id,
  loss_client_id = excluded.loss_client_id,
  loss_client_name = excluded.loss_client_name,
  loss_piece_id = excluded.loss_piece_id,
  loss_piece_name = excluded.loss_piece_name,
  lost_by_uid = excluded.lost_by_uid,
  lost_by_name = excluded.lost_by_name,
  lost_at = excluded.lost_at,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;
