insert into public.materials (id, name, price_per_m2, base_cost_per_m2, base_minimum_sale_per_m2, margin_percentage, provider, category, material_line, material_type, thickness_label, texture, image_url, active, source_inventory_id, created_at, updated_at)
values
  ('alba-oro', 'Alba Oro', 0, 0, null, 0, '', 'Mármore', 'Premium', 'Chapa', '2cm', 'Polido', null, true, null, timezone('utc', now()), '2026-05-21T14:16:21.257Z'::timestamptz),
  ('v9wDQoMjHmsRM22JvyoS', 'Preto São Gabriel', 0, 0, null, 0, '', 'Granito', 'Nacional', 'Chapa', '2cm', 'Polido', null, true, null, '2026-05-21T16:43:56.764Z'::timestamptz, '2026-05-21T16:43:56.764Z'::timestamptz),
  ('verde-ubatuba', 'Verde ubatuba', 0, 0, null, 0, '', 'Granito', 'Nacional', 'Chapa', '2cm', 'Polido', null, true, null, timezone('utc', now()), '2026-05-21T16:26:53.813Z'::timestamptz),
  ('statuario', 'Statuario', 0, 0, null, 0, '', 'Lamina Ultracompacta', 'Lamina Ultracompacta', 'Lamina', '6mm', 'Polido', null, true, null, timezone('utc', now()), '2026-05-19T16:12:57.723Z'::timestamptz),
  ('quartzito-naica', 'Quartzito Naica', 0, 0, null, 0, '', 'Quartzito', 'Premium', 'Chapa', null, 'Polido', null, true, null, timezone('utc', now()), '2026-05-21T14:15:26.465Z'::timestamptz),
  ('white-eve-kalahary', 'White eve (Kalahary)', 0, 0, null, 0, '', 'Quartzito', 'Super Premium', 'Chapa', '2cm', 'Polido', null, true, null, timezone('utc', now()), '2026-05-21T14:32:33.021Z'::timestamptz),
  ('patagonia', 'Patagônia', 0, 0, null, 0, '', 'Quartzito', 'Super Premium', 'Chapa', '2cm', 'Polido', null, true, null, timezone('utc', now()), '2026-05-21T14:18:44.545Z'::timestamptz),
  ('branco-siena', 'Branco siena', 0, 0, null, 0, '', 'Granito', 'Nacional', 'Chapa', '2cm', 'Acetinado', null, true, null, timezone('utc', now()), '2026-05-21T14:24:17.447Z'::timestamptz),
  ('taj-mahal', 'Taj Mahal', 0, 0, null, 0, '', 'Lamina Ultracompacta', 'Premium', 'Lamina', '6mm', 'Polido', null, true, null, timezone('utc', now()), '2026-05-21T14:25:26.939Z'::timestamptz),
  ('preto-absoluto', 'Preto absoluto', 0, 0, null, 0, '', 'Granito', 'Nacional', 'Chapa', '2cm', 'Polido', null, true, null, timezone('utc', now()), '2026-05-21T14:24:47.209Z'::timestamptz),
  ('quartzito-botanic-green', 'Botanic Green', 0, 0, null, 0, '', 'Quartzito', 'Super Premium', 'Chapa', '2cm', 'Polido', null, true, null, timezone('utc', now()), '2026-05-21T14:17:49.728Z'::timestamptz),
  ('gucci', 'Gucci', 0, 0, null, 0, '', 'Quartzito', 'Super Premium', 'Chapa', '2cm', 'Polido', null, true, null, timezone('utc', now()), '2026-05-21T14:35:19.860Z'::timestamptz),
  ('new-taj', 'New Taj', 0, 0, null, 0, '', 'Lâmina Ultracompacta', 'Premium', 'Lamina', '6mm', 'Acetinado', null, true, null, timezone('utc', now()), '2026-05-21T14:19:46.946Z'::timestamptz),
  ('branco-itaunas', 'Branco itaunas', 0, 0, null, 0, '', 'Granito', 'Granito', 'Chapa', '2cm', null, null, true, null, timezone('utc', now()), '2026-05-19T16:12:18.432Z'::timestamptz),
  ('branco-parana-calacata', 'Branco Paraná Calacata', 0, 0, null, 0, '', 'Mármore', 'Premium', 'Chapa', '2cm', 'Polido', null, true, null, timezone('utc', now()), '2026-05-21T14:14:55.937Z'::timestamptz),
  ('perla', 'Perla', 0, 0, null, 0, '', 'Quartzito', 'Premium', 'Chapa', '2cm', 'Polido', null, true, null, timezone('utc', now()), '2026-05-21T14:32:03.266Z'::timestamptz),
  ('verdant', 'Verdant', 0, 0, null, 0, '', 'Quartzito', 'Super Premium', 'Chapa', '2cm', 'Polido', null, true, null, timezone('utc', now()), '2026-05-21T14:22:33.602Z'::timestamptz),
  ('quartzo-branco', 'Quartzo branco', 0, 0, null, 0, '', 'Quartzo', 'Premium', 'Chapa', '2cm', 'Polido', null, true, null, timezone('utc', now()), '2026-05-21T14:25:05.762Z'::timestamptz),
  ('green-spectrun', 'Green Spectrun', 0, 0, null, 0, '', 'Quartzito', 'Premium', 'Chapa', '2cm', 'Polido', null, true, null, timezone('utc', now()), '2026-05-21T14:11:06.381Z'::timestamptz),
  ('verde-guatemala', 'Verde Guatemala', 0, 0, null, 0, '', 'Mármore', 'Premium', 'Chapa', '2cm', 'Polido', null, true, null, timezone('utc', now()), '2026-05-21T14:20:16.079Z'::timestamptz),
  ('branco-parana', 'Branco paraná', 0, 0, null, 0, '', 'Marmore', 'Marmore', 'Chapa', '2cm', 'Polido', null, true, null, timezone('utc', now()), '2026-05-19T16:13:49.081Z'::timestamptz),
  ('preto-sao-gabriel', 'Preto São Gabriel', 0, 0, null, 0, '', 'Granito', 'Nacional', 'Chapa', '2cm', 'Escovado', null, true, null, timezone('utc', now()), '2026-05-21T16:27:31.022Z'::timestamptz),
  ('banco-pinta-verde', 'Branco pinta verde', 0, 0, null, 0, '', 'Granito', 'Granito', 'Chapa', '2cm', 'Polido', null, true, null, timezone('utc', now()), '2026-05-21T12:03:34.086Z'::timestamptz)
on conflict (id) do update set
  name = excluded.name,
  price_per_m2 = excluded.price_per_m2,
  base_cost_per_m2 = excluded.base_cost_per_m2,
  base_minimum_sale_per_m2 = excluded.base_minimum_sale_per_m2,
  margin_percentage = excluded.margin_percentage,
  provider = excluded.provider,
  category = excluded.category,
  material_line = excluded.material_line,
  material_type = excluded.material_type,
  thickness_label = excluded.thickness_label,
  texture = excluded.texture,
  image_url = excluded.image_url,
  active = excluded.active,
  source_inventory_id = excluded.source_inventory_id,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;
