insert into public.users (id, auth_user_id, nome, name, email, role, permissions, blocked, created_at, updated_at, updated_by_uid, updated_by_email, updated_by_name)
values
  ('oQEE1LSKn3Rt4T9jUML4Ih4k2we2', null, 'Wellington Oliveira', 'Wellington Oliveira', 'welfernandes08@hotmail.com', 'liberacao', '{"dashboard":{"visualizar":true},"orcamento":{"visualizar":true,"criar":false,"editar":false,"excluir":false,"aprovar":false},"historico":{"visualizar":true},"materiais":{"visualizar":true,"editar":false},"estoque":{"visualizar":true,"adicionar":false,"editar":false,"excluir":false,"movimentar":false},"relatorios":{"visualizar":true,"exportar":false,"verFaturamento":false,"verProdutividade":false},"admin":{"visualizarUsuarios":false,"alterarPermissoes":false,"excluirUsuarios":false},"cliente":{"visualizar":true,"editarDados":false,"alterarEtapa":false,"anexarArquivos":false,"avaliarFuncionarios":false},"medicao":{"visualizar":true,"criar":false,"editar":false},"projeto":{"visualizar":true,"criar":false,"editar":false,"aprovar":true},"producao":{"visualizar":true,"alterarEtapa":true,"conferirMedidas":true,"finalizarProducao":true},"liberacao":{"visualizar":true,"aprovar":true,"reprovar":true}}'::jsonb, false, '2026-05-20T12:54:15.889Z'::timestamptz, '2026-05-20T13:32:04.133Z'::timestamptz, 'JPSHn4Zeq4RhmdQO313pIW4mVJH2', 'brian_takiya77@outlook.com', 'brian_takiya77'),
  ('a7HNZZyjLtZ9vwK2quKJzaCKaf73', null, 'vinny.iprisd', 'vinny.iprisd', 'vinny.iprisd@gmail.com', 'vendedor', '{"dashboard":{"visualizar":true},"orcamento":{"visualizar":true,"criar":true,"editar":true,"excluir":true,"aprovar":true},"historico":{"visualizar":true},"materiais":{"visualizar":true,"editar":false},"estoque":{"visualizar":true,"adicionar":false,"editar":false,"excluir":false,"movimentar":false},"relatorios":{"visualizar":true,"exportar":false,"verFaturamento":false,"verProdutividade":false},"admin":{"visualizarUsuarios":false,"alterarPermissoes":false,"excluirUsuarios":false},"cliente":{"visualizar":true,"editarDados":true,"alterarEtapa":true,"anexarArquivos":true,"avaliarFuncionarios":false},"medicao":{"visualizar":true,"criar":true,"editar":true},"projeto":{"visualizar":true,"criar":true,"editar":true,"aprovar":false},"producao":{"visualizar":true,"alterarEtapa":false,"conferirMedidas":false,"finalizarProducao":false},"liberacao":{"visualizar":true,"aprovar":false,"reprovar":false}}'::jsonb, false, '2026-05-13T15:40:57.116Z'::timestamptz, '2026-05-20T13:31:41.618Z'::timestamptz, 'JPSHn4Zeq4RhmdQO313pIW4mVJH2', 'brian_takiya77@outlook.com', 'brian_takiya77'),
  ('lr7O5vB69Zf5JuxgKkb5Q5ib1Am1', null, 'Jéssica Rodrigues Leite Benedito', 'Jéssica Rodrigues Leite Benedito', 'jhessypresentes.s2@gmail.com', 'administrativo', '{"dashboard":{"visualizar":true},"orcamento":{"visualizar":true,"criar":false,"editar":false,"excluir":false,"aprovar":false},"historico":{"visualizar":true},"materiais":{"visualizar":true,"editar":true},"estoque":{"visualizar":true,"adicionar":true,"editar":true,"excluir":true,"movimentar":true},"relatorios":{"visualizar":true,"exportar":true,"verFaturamento":true,"verProdutividade":true},"admin":{"visualizarUsuarios":false,"alterarPermissoes":false,"excluirUsuarios":false},"cliente":{"visualizar":true,"editarDados":true,"alterarEtapa":false,"anexarArquivos":true,"avaliarFuncionarios":false},"medicao":{"visualizar":true,"criar":false,"editar":false},"projeto":{"visualizar":true,"criar":false,"editar":false,"aprovar":false},"producao":{"visualizar":true,"alterarEtapa":false,"conferirMedidas":false,"finalizarProducao":false},"liberacao":{"visualizar":true,"aprovar":false,"reprovar":false}}'::jsonb, false, '2026-05-14T13:46:35.266Z'::timestamptz, '2026-05-20T13:30:35.849Z'::timestamptz, 'JPSHn4Zeq4RhmdQO313pIW4mVJH2', 'brian_takiya77@outlook.com', 'brian_takiya77'),
  ('JPSHn4Zeq4RhmdQO313pIW4mVJH2', null, 'brian_takiya77', 'brian_takiya77', 'brian_takiya77@outlook.com', 'administrativo', '{"orcamento":{"visualizar":false,"criar":false,"editar":false,"excluir":false,"aprovar":false},"estoque":{"visualizar":true,"adicionar":true,"editar":true,"excluir":true,"movimentar":true},"relatorios":{"visualizar":true,"exportar":true,"verFaturamento":true,"verProdutividade":false},"admin":{"visualizarUsuarios":false,"alterarPermissoes":false,"excluirUsuarios":false},"cliente":{"visualizar":true,"editarDados":true,"alterarEtapa":false,"anexarArquivos":true,"avaliarFuncionarios":false},"medicao":{"visualizar":true,"criar":false,"editar":false},"projeto":{"visualizar":true,"criar":false,"editar":false,"aprovar":false},"producao":{"visualizar":false,"alterarEtapa":false,"conferirMedidas":false,"finalizarProducao":false},"liberacao":{"visualizar":false,"aprovar":false,"reprovar":false}}'::jsonb, false, '2026-05-12T20:08:33.918Z'::timestamptz, '2026-05-12T20:08:33.918Z'::timestamptz, null, null, null),
  ('VlN44VojjDaGp2AVF398Gc3btiD3', null, 'fabioduarte232', 'fabioduarte232', 'fabioduarte232@yahoo.com', 'administrativo', '{"dashboard":{"visualizar":true},"orcamento":{"visualizar":true,"criar":false,"editar":false,"excluir":false,"aprovar":false},"historico":{"visualizar":true},"materiais":{"visualizar":true,"editar":false},"estoque":{"visualizar":true,"adicionar":false,"editar":false,"excluir":false,"movimentar":false},"relatorios":{"visualizar":true,"exportar":true,"verFaturamento":true,"verProdutividade":true},"admin":{"visualizarUsuarios":false,"alterarPermissoes":false,"excluirUsuarios":false},"cliente":{"visualizar":true,"editarDados":true,"alterarEtapa":true,"anexarArquivos":true,"avaliarFuncionarios":true},"medicao":{"visualizar":true,"criar":true,"editar":true},"projeto":{"visualizar":true,"criar":false,"editar":false,"aprovar":true},"producao":{"visualizar":true,"alterarEtapa":true,"conferirMedidas":true,"finalizarProducao":true},"liberacao":{"visualizar":true,"aprovar":true,"reprovar":true}}'::jsonb, false, '2026-05-19T20:43:02.089Z'::timestamptz, '2026-05-20T13:30:13.118Z'::timestamptz, 'JPSHn4Zeq4RhmdQO313pIW4mVJH2', 'brian_takiya77@outlook.com', 'brian_takiya77'),
  ('teaHQJYhs6YKcqKbuAj7Jli96sI2', null, 'brunocraftertb', 'brunocraftertb', 'brunocraftertb@gmail.com', 'administrativo', '{"dashboard":{"visualizar":true},"orcamento":{"visualizar":true,"criar":true,"editar":true,"excluir":true,"aprovar":true},"historico":{"visualizar":true},"materiais":{"visualizar":true,"editar":true},"estoque":{"visualizar":true,"adicionar":true,"editar":true,"excluir":true,"movimentar":true},"relatorios":{"visualizar":true,"exportar":true,"verFaturamento":true,"verProdutividade":false},"admin":{"visualizarUsuarios":true,"alterarPermissoes":false,"excluirUsuarios":false},"cliente":{"visualizar":true,"editarDados":true,"alterarEtapa":true,"anexarArquivos":true,"avaliarFuncionarios":true},"medicao":{"visualizar":true,"criar":true,"editar":true},"projeto":{"visualizar":true,"criar":true,"editar":true,"aprovar":true},"producao":{"visualizar":true,"alterarEtapa":true,"conferirMedidas":true,"finalizarProducao":true},"liberacao":{"visualizar":true,"aprovar":true,"reprovar":true}}'::jsonb, false, '2026-05-18T17:41:28.187Z'::timestamptz, '2026-05-20T13:29:30.063Z'::timestamptz, 'JPSHn4Zeq4RhmdQO313pIW4mVJH2', 'brian_takiya77@outlook.com', 'brian_takiya77'),
  ('oMgxor0aUPUPVrNNK1Q5E4hLjC63', null, 'rafael.edf25', 'rafael.edf25', 'rafael.edf25@gmail.com', 'administrativo', '{"dashboard":{"visualizar":true},"orcamento":{"visualizar":true,"criar":true,"editar":true,"excluir":true,"aprovar":true},"historico":{"visualizar":true},"materiais":{"visualizar":true,"editar":true},"estoque":{"visualizar":true,"adicionar":true,"editar":true,"excluir":true,"movimentar":true},"relatorios":{"visualizar":true,"exportar":true,"verFaturamento":true,"verProdutividade":true},"admin":{"visualizarUsuarios":true,"alterarPermissoes":true,"excluirUsuarios":true},"cliente":{"visualizar":true,"editarDados":true,"alterarEtapa":true,"anexarArquivos":true,"avaliarFuncionarios":true},"medicao":{"visualizar":true,"criar":true,"editar":true},"projeto":{"visualizar":true,"criar":true,"editar":true,"aprovar":true},"producao":{"visualizar":true,"alterarEtapa":true,"conferirMedidas":true,"finalizarProducao":true},"liberacao":{"visualizar":true,"aprovar":true,"reprovar":true}}'::jsonb, false, '2026-05-12T20:20:21.714Z'::timestamptz, '2026-05-20T13:30:50.869Z'::timestamptz, 'JPSHn4Zeq4RhmdQO313pIW4mVJH2', 'brian_takiya77@outlook.com', 'brian_takiya77'),
  ('zSxmWGUnKvc8XO4gyyoA630ypq22', null, 'rhhirakawa', 'rhhirakawa', 'rhhirakawa@gmail.com', 'administrativo', '{"dashboard":{"visualizar":true},"orcamento":{"visualizar":true,"criar":false,"editar":false,"excluir":false,"aprovar":false},"historico":{"visualizar":true},"materiais":{"visualizar":true,"editar":true},"estoque":{"visualizar":true,"adicionar":true,"editar":true,"excluir":true,"movimentar":true},"relatorios":{"visualizar":true,"exportar":true,"verFaturamento":true,"verProdutividade":true},"admin":{"visualizarUsuarios":false,"alterarPermissoes":false,"excluirUsuarios":false},"cliente":{"visualizar":true,"editarDados":true,"alterarEtapa":false,"anexarArquivos":true,"avaliarFuncionarios":false},"medicao":{"visualizar":true,"criar":false,"editar":false},"projeto":{"visualizar":true,"criar":false,"editar":false,"aprovar":false},"producao":{"visualizar":true,"alterarEtapa":false,"conferirMedidas":false,"finalizarProducao":false},"liberacao":{"visualizar":true,"aprovar":false,"reprovar":false}}'::jsonb, false, '2026-05-13T15:44:29.920Z'::timestamptz, '2026-05-20T13:31:12.528Z'::timestamptz, 'JPSHn4Zeq4RhmdQO313pIW4mVJH2', 'brian_takiya77@outlook.com', 'brian_takiya77')
on conflict (id) do update set
  auth_user_id = excluded.auth_user_id,
  nome = excluded.nome,
  name = excluded.name,
  email = excluded.email,
  role = excluded.role,
  permissions = excluded.permissions,
  blocked = excluded.blocked,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  updated_by_uid = excluded.updated_by_uid,
  updated_by_email = excluded.updated_by_email,
  updated_by_name = excluded.updated_by_name;
