export const LABELS = {
  common: {
    actions: 'Ações',
    area: 'Área',
    squareMeter: 'm²',
    loading: 'Carregando...',
    save: 'Salvar',
  },
  search: {
    globalPlaceholder: 'Busca global por cliente, orçamento, lote, pedra ou fornecedor...',
    quickResults: 'Resultados rápidos',
    noResults: 'Nenhum resultado encontrado para essa busca.',
  },
  quotes: {
    singular: 'Orçamento',
    plural: 'Orçamentos',
    new: 'Novo Orçamento',
    edit: 'Editar Orçamento',
    save: 'Salvar Orçamento',
    created: 'Orçamento criado',
    updated: 'Orçamento atualizado',
    duplicated: 'Orçamento duplicado',
    deleted: 'Orçamento excluído',
    openFilter: 'Filtro ativo: Orçamentos em aberto',
    listTitle: 'Orçamento / Cliente',
    empty: 'Nenhum orçamento encontrado.',
    loading: 'Carregando orçamentos...',
    pageDescription: 'Crie e gerencie orçamentos e pedidos.',
    editorDescription: 'Configure as peças, materiais e condições.',
  },
  pieces: {
    singular: 'Peça',
    plural: 'Peças',
    quotePieces: 'Peças do Orçamento',
    add: 'Adicionar Peça',
    draw: 'Desenhar Peça',
    remove: 'Remover peça',
  },
} as const;
