drop policy if exists "authenticated_full_access_profiles" on public.profiles;
create policy "authenticated_full_access_profiles" on public.profiles for all to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null);
drop policy if exists "authenticated_full_access_users" on public.users;
create policy "authenticated_full_access_users" on public.users for all to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null);
drop policy if exists "authenticated_full_access_settings" on public.settings;
create policy "authenticated_full_access_settings" on public.settings for all to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null);
drop policy if exists "authenticated_full_access_condominiums" on public.condominiums;
create policy "authenticated_full_access_condominiums" on public.condominiums for all to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null);
drop policy if exists "authenticated_full_access_clients" on public.clients;
create policy "authenticated_full_access_clients" on public.clients for all to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null);
drop policy if exists "authenticated_full_access_employees" on public.employees;
create policy "authenticated_full_access_employees" on public.employees for all to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null);
drop policy if exists "authenticated_full_access_materials" on public.materials;
create policy "authenticated_full_access_materials" on public.materials for all to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null);
drop policy if exists "authenticated_full_access_user_material_prices" on public.user_material_prices;
create policy "authenticated_full_access_user_material_prices" on public.user_material_prices for all to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null);
drop policy if exists "authenticated_full_access_quotes" on public.quotes;
create policy "authenticated_full_access_quotes" on public.quotes for all to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null);
drop policy if exists "authenticated_full_access_yard_racks" on public.yard_racks;
create policy "authenticated_full_access_yard_racks" on public.yard_racks for all to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null);
drop policy if exists "authenticated_full_access_inventory" on public.inventory;
create policy "authenticated_full_access_inventory" on public.inventory for all to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null);
drop policy if exists "authenticated_full_access_inventory_reservations" on public.inventory_reservations;
create policy "authenticated_full_access_inventory_reservations" on public.inventory_reservations for all to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null);
drop policy if exists "authenticated_full_access_inventory_purchases" on public.inventory_purchases;
create policy "authenticated_full_access_inventory_purchases" on public.inventory_purchases for all to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null);
drop policy if exists "authenticated_full_access_fixture_catalog" on public.fixture_catalog;
create policy "authenticated_full_access_fixture_catalog" on public.fixture_catalog for all to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null);
drop policy if exists "authenticated_full_access_calendar_events" on public.calendar_events;
create policy "authenticated_full_access_calendar_events" on public.calendar_events for all to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null);
drop policy if exists "authenticated_full_access_dashboard_notes" on public.dashboard_notes;
create policy "authenticated_full_access_dashboard_notes" on public.dashboard_notes for all to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null);
drop policy if exists "authenticated_full_access_system_events" on public.system_events;
create policy "authenticated_full_access_system_events" on public.system_events for all to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null);
drop policy if exists "authenticated_full_access_audit_logs" on public.audit_logs;
create policy "authenticated_full_access_audit_logs" on public.audit_logs for all to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null);
